---
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-burstable
  labels:
    name: qos-demo-burstable
spec:
  containers:
    - name: qos-demo-burstable
      image: nginx
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
